# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://vlan101.net"
title = "vlan101.net - Rambling of a Network Engineer"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = false     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: params.author.name ↓ # 默认为下面配置的params.author.name ↓

[pagination]
  pagerSize = 5           # Number of articles displayed on the homepage  # 首页每页显示的文章数

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
[languages.en]
  languageCode = "en"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  pageref = "/"
[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  pageref = "/post/"
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  pageref = "/tags/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  since = "2025"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  author.name = "Stephen Santos"      # essential                     # 必需
  author.email = "stephen.santos@vlan101.net" # optional, for RSS             # 可选
  author.url = "/about"        # optional                      # 可选

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "vlan101.net"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["vlan101.net", "networking", "cisco", "fortinet", "palo alto"]
  description = "Ramblings of a Network Engineer."

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  [params.social]                                         # 社交链接
    a-email = "stephen.santos@vlan101.net"
    b-stack-overflow = ""
    c-twitter = "https://x.com/vlan101net"
    d-facebook = ""
    e-linkedin = "https://www.linkedin.com/in/stephen-santos-4b421910/"
    f-google = ""
    g-github = "https://github.com/vlan101net"
    h-weibo = ""
    i-zhihu = ""
    j-douban = ""
    k-pocket = ""
    l-tumblr = ""
    m-instagram = ""
    n-gitlab = ""
    o-goodreads = ""
    p-coding = ""
    q-bilibili = ""
    r-codeforces = ""
    s-mastodon = ""
    t-youtube = ""
    u-twitch = ""
