baseURL = 'https://vlan101.net/'
title = 'vlan101.net'
author = 'Stephen Santos'
copyright = 'Stephen Santos'
pagination.pagerSize = 5
languageCode = 'en-us'
theme = 'tailwind'

[markup]
  _merge = "deep"

[params]
  contentTypeName = 'posts'

  [param.header]
    logo = 'logo.png'
    title = ''

  [param.footer]
    since = 2025
    poweredby = false

[menu]

  [[menu.main]]
    indentifier = 'post'
    name = 'Post'
    pageRef = '/posts'
    weight = 10

  [[menu.main]]
    identifier = 'about'
    name = 'About'
    pageRef = '/about'
    weight = 20

[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

[caches]
  [caches.images]
    dir = ':cacheDir/images'